version: '3.8'

services:

  server:
    build:
      context: ./server
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true
